function onLoad()
	io.write("Calling onLoad\n")
	create_entity("player", 10, 10, 0)
	--create_entity("fire", 5, 5, 0)
	--create_entity("fire", 20, 5, 0)
	--create_entity("fire", 35, 5, 0)
	--create_entity("fire", 5, 20, 0)
	--create_entity("fire", 40, 20, 0)
	io.write("onLoad finished\n")
end